version: '3'
services:
    web: #current 1.21.6
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./src:/src
    php:  #current 8.1.3
        build:
          context: .
          dockerfile: PHP.dockerfile
        volumes:
            - ./src:/src
        ports:
            - "8765:8765"
    mysql: #current 8.0.28
        image: mysql:latest
        ports:
          - 3307:3306
        environment:
          MYSQL_ROOT_PASSWORD: "290920"
          MYSQL_PASSWORD: "290920"
          MYSQL_USER: "long"
          MYSQL_DATABASE: "webchat"
